[package]
name = "flang"
version = "0.1.0"
authors = ["Lorxu <sam@dirkback.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
logging = []

[dependencies]
lazy_static = "*"
lalrpop-util = "*"
regex = "1"
codespan-reporting = "*"
rustyline = "*"

[build-dependencies]
lalrpop = { version = "*", features = ["lexer"]}
