name: Rust

on:
  push:
    branches: [ "next" ]
  pull_request:
    branches: [ "next" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
                 
    - name: Run tests and generate coverage
      uses: actions-rs/tarpaulin@v0.1.0
      with:
        out-type: Lcov

    - name: Upload code coverage
      uses: coverallsapp/github-action@v2
