name: Rust

on:
  push:
    branches: [ "next" ]
  pull_request:
    branches: [ "next" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download cargo-tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Run tests and generate coverage
      run: cargo tarpaulin --out lcov

    - name: Upload code coverage
      uses: coverallsapp/github-action@v2
